/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OpinieRouteImport } from './routes/opinie'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSendEmailRouteImport } from './routes/api/send-email'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinieRoute = OpinieRouteImport.update({
  id: '/opinie',
  path: '/opinie',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendEmailRoute = ApiSendEmailRouteImport.update({
  id: '/api/send-email',
  path: '/api/send-email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/oferta': typeof OfertaRoute
  '/opinie': typeof OpinieRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/send-email': typeof ApiSendEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/oferta': typeof OfertaRoute
  '/opinie': typeof OpinieRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/send-email': typeof ApiSendEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/oferta': typeof OfertaRoute
  '/opinie': typeof OpinieRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/send-email': typeof ApiSendEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeria'
    | '/kontakt'
    | '/oferta'
    | '/opinie'
    | '/sitemap.xml'
    | '/api/send-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeria'
    | '/kontakt'
    | '/oferta'
    | '/opinie'
    | '/sitemap.xml'
    | '/api/send-email'
  id:
    | '__root__'
    | '/'
    | '/galeria'
    | '/kontakt'
    | '/oferta'
    | '/opinie'
    | '/sitemap.xml'
    | '/api/send-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriaRoute: typeof GaleriaRoute
  KontaktRoute: typeof KontaktRoute
  OfertaRoute: typeof OfertaRoute
  OpinieRoute: typeof OpinieRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSendEmailRoute: typeof ApiSendEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opinie': {
      id: '/opinie'
      path: '/opinie'
      fullPath: '/opinie'
      preLoaderRoute: typeof OpinieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-email': {
      id: '/api/send-email'
      path: '/api/send-email'
      fullPath: '/api/send-email'
      preLoaderRoute: typeof ApiSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriaRoute: GaleriaRoute,
  KontaktRoute: KontaktRoute,
  OfertaRoute: OfertaRoute,
  OpinieRoute: OpinieRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSendEmailRoute: ApiSendEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
